# Generated by Django 4.2.9 on 2024-04-21 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroir', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date',
            new_name='date_joined',
        ),
        migrations.RemoveField(
            model_name='image',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pointage',
            name='increment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='pointage',
            name='etat',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointage',
            name='hour',
            field=models.TimeField(blank=True, default=datetime.time(16, 25, 18, 394559)),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 4, 21)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Psychology',
        ),
    ]
