# Generated by Django 4.2.9 on 2024-04-28 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroir', '0002_rename_date_user_date_joined_remove_image_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 4, 28)),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='hour',
            field=models.TimeField(blank=True, default=datetime.time(9, 20, 32, 173787)),
        ),
    ]
