# Generated by Django 4.2.9 on 2024-05-01 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroir', '0003_alter_pointage_date_alter_pointage_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Problemme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, default=datetime.date(2024, 5, 1))),
                ('hour', models.TimeField(blank=True, default=datetime.time(8, 12, 35, 664346))),
            ],
        ),
        migrations.AlterField(
            model_name='pointage',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 1)),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='hour',
            field=models.TimeField(blank=True, default=datetime.time(8, 12, 35, 663347)),
        ),
    ]
