# Generated by Django 4.2.9 on 2024-05-02 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroir', '0004_image_problemme_alter_pointage_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='autorisation',
            field=models.CharField(default='0000000000', max_length=30),
        ),
        migrations.AlterField(
            model_name='image_problemme',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 2)),
        ),
        migrations.AlterField(
            model_name='image_problemme',
            name='hour',
            field=models.TimeField(blank=True, default=datetime.time(21, 58, 9, 500263)),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 2)),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='hour',
            field=models.TimeField(blank=True, default=datetime.time(21, 58, 9, 500263)),
        ),
    ]
