# Generated by Django 4.2.9 on 2024-05-04 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroir', '0005_role_autorisation_alter_image_problemme_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_problemme',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 4)),
        ),
        migrations.AlterField(
            model_name='image_problemme',
            name='hour',
            field=models.TimeField(blank=True, default=datetime.time(16, 56, 45, 628767)),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 4)),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='hour',
            field=models.TimeField(blank=True, default=datetime.time(16, 56, 45, 628767)),
        ),
    ]
