# Generated by Django 4.2.9 on 2024-05-05 14:12

import datetime
from django.db import migrations, models
import miroir.models


class Migration(migrations.Migration):

    dependencies = [
        ('miroir', '0006_alter_image_problemme_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_problemme',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 5)),
        ),
        migrations.AlterField(
            model_name='image_problemme',
            name='hour',
            field=models.TimeField(blank=True, default=miroir.models.time_without_seconds),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 5)),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='hour',
            field=models.TimeField(blank=True, default=datetime.time(14, 12, 41, 680477)),
        ),
    ]
