# Generated by Django 4.2.9 on 2024-05-05 14:20

from django.db import migrations, models
import miroir.models


class Migration(migrations.Migration):

    dependencies = [
        ('miroir', '0007_alter_image_problemme_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='hour',
            field=models.TimeField(blank=True, default=miroir.models.time_without_seconds),
        ),
    ]
